修改yaml文件

diff --git a/.github/workflows/protocal.yml b/.github/workflows/protocal.yml
--- a/.github/workflows/protocal.yml
+++ b/.github/workflows/protocal.yml
@@ -24,11 +24,15 @@ jobs:
 
       - name: Extract Release Version
         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
+      
+      - name: Check file existence and location
+        run: |
+          ls -la
+          find . -name "run.sh" || echo "run.sh not found in repository"
 
       - name: Generate for Golang
         shell: bash
         run: |
           # 针对每个 service 生成 Go 源码
-          chmod +x run.sh
-          run.sh "${{ matrix.service }}" "${{ env.RELEASE_VERSION }}"
-          
+          chmod +x ./run.sh
+          ./run.sh "${{ matrix.service }}" "${{ env.RELEASE_VERSION }}"
